sudo: false

language: python
python:
  - "3.7"

# This appears to be the only distribution with Python 3.7 support at the
# moment:
#
#   https://github.com/travis-ci/travis-ci/issues/9815
#
dist: xenial

install:
  - pip3 install -e .[dev]
  - pip3 install opencv-python
  - pip3 check

script:
  - ./meta/run_tests.sh
