sudo: false

language: python
python:
  - "3.6"

install:
  - pip3 install -e .[dev]
  - pip3 check

script:
  # Only run non-runtime tests until we can get opencv working under Travis.
  # - ./meta/run_tests.sh
  - ./meta/autofix.sh
  - git diff --exit-code
  - ./meta/static_tests.sh
