#! /usr/bin/env python
"""Train 'automark2'."""

import argparse
import json
import sys

import pytorch_lightning as pl
import wandb


import mel.rotomap.moles
import mel.lib.common
import mel.rotomap.detectmolesnn


def setup_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--train",
        metavar="PTGZ_FILE",
        nargs="+",
        help="A list of paths to pre-trained images to process.",
        required=True,
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Print information about the processing.",
    )
    return parser


def main():
    parser = setup_parser()
    args = parser.parse_args()

    enable_wandb = False

    experiment_name = (
        "dense_1cyclelr_600epochs_075lr_defaultdiv_defaultanneal_blur64"
    )

    # Import this as lazily as possible as it takes a while to import, so that
    # we only pay the import cost when we use it.
    import torch

    melroot = mel.lib.fs.find_melroot()
    model_dir = melroot / mel.lib.fs.DEFAULT_CLASSIFIER_PATH
    model_path = model_dir / "automark2.pth"
    metadata_path = model_dir / "automark2.json"
    print(f"Will save to {model_path}")
    print(f"         and {metadata_path}")

    model = mel.rotomap.detectmolesnn.CackModel()

    if enable_wandb:
        wandb_logger = pl.loggers.WandbLogger(
            project="mel-automark2", name=experiment_name
        )
        wandb_logger.watch(model, log="all")

    train_dl = torch.utils.data.DataLoader(
        args.train,
        batch_size=2,
        shuffle=True,
        collate_fn=mel.rotomap.detectmolesnn.collate,
    )

    trainer_kwargs = {
        "max_steps": model.total_steps,
        "log_every_n_steps": 1,
        "callbacks": [mel.rotomap.detectmolesnn.GlobalProgressBar()],
    }
    if enable_wandb:
        trainer_kwargs["logger"] = wandb_logger
    trainer = pl.Trainer(**trainer_kwargs)

    metadata = {}

    trainer.fit(model, train_dl)

    torch.save(model.state_dict(), model_path)

    if enable_wandb:
        wandb.finish()

    print(f"Saved {model_path}")
    with open(metadata_path, "w") as f:
        json.dump(metadata, f)
        print(f"Saved {metadata_path}")


if __name__ == "__main__":
    sys.exit(main())
