# This is a basic workflow to help you get started with Actions

name: tests

# 'workflow_dispatch' is manually from the Actions tab
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pip3 install -r requirements.txt
          pip3 install -e .[dev] --no-deps
          #pip3 check

      - name: Test
        run: ./meta/run_tests.sh
